### ISSUE TITLE
[Feature] Category for benefit 

### ISSUE THREAD

**Issue by hoailinh1210** [VK-Lab/mlem-dashboard#19]
**Is your feature request related to a problem? Please describe.**

Many users on our platform have requested a way to categorize benefits based on their type or purpose. Currently, it can be difficult to sort through a long list of benefits to find the ones that are most relevant to a user's needs.

**Describe the solution you'd like**

I would like to see a new feature added to the platform that allows users to categorize benefits based on their type or purpose. This could be done by adding a "Category" field to the benefits form, which would allow users to select from a predefined list of categories (such as "Healthcare", "Retirement", "Education", etc.) or create their own custom categories. Users would then be able to filter benefits by category on the benefits page, making it easier to find the benefits that are most relevant to them.

**Describe alternatives you've considered**

One alternative solution could be to allow users to tag benefits with keywords or phrases, rather than assigning them to a specific category. This would give users more flexibility in how they categorize their benefits, but could also lead to inconsistency in how benefits are labeled. Another alternative could be to improve the search functionality on the benefits page, making it easier for users to find benefits based on keywords or phrases.

**Additional context**

Adding a category field to the benefits form would not only benefit our users, but would also make it easier for us to analyze and report on benefit usage by category. This information could be used to make data-driven decisions about which benefits to offer or promote to our users.

**Comment by gaupoit** [comment]
![Screenshot 2023-05-18 at 10 30 25](https://github.com/VK-Lab/mlem-dashboard/assets/4486806/2c77865b-7f84-44ba-8d92-0726795de44b)
