### ISSUE TITLE
[Feature] Integrate with WooCommerce/Shopify to generate coupon code when user claim Benefit

### ISSUE THREAD

**Issue by hoailinh1210** [VK-Lab/mlem-dashboard#21]
**Describe the solution you'd like**

I would like to request the integration of WooCommerce/Shopify into our platform to generate coupon codes when a user claims a benefit. This integration would allow us to generate unique coupon codes for each benefit that is claimed, which would be sent to the user displayed on the benefits page. The coupon codes could then be redeemed in a physical/web store

Integrated platform:

- [x] WooCommerce

**Comment by gaupoit** [comment]
I will reduce the scope of this task which cover WooCommerce first.
